CHAR_FIELD_MAX_LENGTH = 200
RECIPE_TEXT_MAX_LENGTH = 1000
HEX_COLOR_FIELD_MAX_LENGTH = 7
COOKING_TIME_MIN_VALUE = 1
INGREDIENT_AMOUNT_MIN_VALUE = 1
DEFAULT_HEX_COLOR = '#CD5C5C'
HEX_COLOR_REGULAR_EXPRESSION = '^#(?:[0-9a-fA-F]{3}){1,2}$'
