# Generated by Django 4.2.5 on 2023-09-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_ingredient_ingredientmeasure_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipes.IngredientMeasure', to='recipes.ingredient', verbose_name='Ингредиенты'),
        ),
    ]
